# Generated by Django 3.2.16 on 2023-02-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230225_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='could_not_follow_itself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower',
        ),
    ]
