# Generated by Django 3.2.16 on 2023-02-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230228_0015'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='could_not_follow_itself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower',
        ),
    ]
